export const CollectionItemActionTypes = {
    FETCH_COLLECTION_ITEM_FAIL: 'FETCH_COLLECTION_ITEM_FAIL',
    FETCH_COLLECTION_ITEM_START: 'FETCH_COLLECTION_ITEM_START',
    FETCH_COLLECTION_ITEM_SUCCESS: 'FETCH_COLLECTION_ITEM_SUCCESS',
    CLEAR_COLLECTION_ITEM_DATA: 'CLEAR_COLLECTION_ITEM_DATA'
}