export const ActionTypes = {
    // FETCH_SUCCESS: 'FETCH_DATA',
    // FETCH_FAIL: 'FETCH_FAIL',
    // FETCH_START: 'FETCH_START',
    // CLEAR_DATA: 'CLEAR_DATA',
    FETCH_SEARCH_ITEMS_START: 'FETCH_SEARCH_ITEMS_START',
    FETCH_SEARCH_ITEMS_SUCCESS: 'FETCH_SEARCH_ITEMS_SUCCESS',
    FETCH_SEARCH_ITEMS_FAIL: 'FETCH_SEARCH_ITEMS_FAIL'
}