export const ActionTypes = {
    FETCH_SUCCESS: 'FETCH_DATA',
    FETCH_FAIL: 'FETCH_FAIL',
    FETCH_START: 'FETCH_START',
    CLEAR_DATA: 'CLEAR_DATA',
    FETCH_CATALOG_START: 'FETCH_CATALOG_START',
    FETCH_CATALOG_SUCCESS: 'FETCH_CATALOG_SUCCESS',
    FETCH_CATALOG_FAIL: 'FETCH_CATALOG_FAIL'
}